### ISSUE TITLE
issues with hex color, missing entry

### ISSUE THREAD

**Issue by daf** [ZoeFiri/base16-summercamp#1]
Hi, two issues that pybase16-builder uncovered:

- `base0C: "5aevvc"` - pybase16 chokes on trying to interpret `ev` as a hex color - i replaced the `vv` with `00` but i'm not sure what color it's supposed to be
- won't complete due to a missing `base0F` entry (i used `ffffff`)

I put in some fake values to get it to complete and it seems fine but you'd probably have a better idea what they should be.

**Comment by belak** [comment]
I ended up using a color dropper on the base0C in the image - it looks like #5aebbc is the correct color.

In terms of a missing base0F, there's nothing that can really be done - builders *should* error out in this instance, but I guess they don't always do that.

**Comment by zoefiri** [comment]
shoot sorry I hoped I fixed that real quick after `pal` couldn't parse it before anyone noticed and then went on vacation, thanks for making an issue on it it's fixed now.

**Comment by daf** [comment]
Thanks - it might still need a `base0F` entry though?  Maybe that depends on which theme builder you use.

**Comment by belak** [comment]
Yeah, this is still missing `base0F`. I'd be happy to re-enable it in the schemes repo once that's fixed.

**Comment by zoefiri** [comment]
@belak 
Damnit I thought the Base16 main repo said 0F was deprecated??? Either way though sorry I'll work something in, thanks for notifying me.

**Comment by belak** [comment]
I think it's meant for deprecated functions, not that the color is deprecated. That's definitely not very clear.

**Comment by amfl** [comment]
Does 46415a7 close this again?

**Comment by belak** [comment]
I believe it does

**Comment by belak** [comment]
This is now resolved and can be closed.
